### ISSUE TITLE
html sections

### ISSUE THREAD

**Issue by rimmesbe** [Rupieeroo/prj-rev-bwfs-dasmoto#1]
Good job creating sections in the HTML with div tags. Make sure you wrap id/class values in quotes "".

https://github.com/Rupieeroo/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/index.html#L12-L17

**Comment by Rupieeroo** [comment]
Ah! always forgetting this, thank you!
