### ISSUE TITLE
setting page font

### ISSUE THREAD

**Issue by rimmesbe** [Rupieeroo/prj-rev-bwfs-dasmoto#4]
Rather then having to set the font-family in each selector you can set the default font for all elements on the page using inheritance:
html { font-family: Helvetica; }
Now all elements will inherit this as their default font.

https://github.com/Rupieeroo/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/Resources/Style.css#L2

**Comment by Rupieeroo** [comment]
Didn't know this, thank you as this will be exponentially useful
