### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [Rupieeroo/prj-rev-bwfs-dasmoto#6]
Grade: Satisfactory

Summary: Nice job on this project, the site looks good. You used some good techniques and kept your code well organized. Take a look at the issues I created as they will point out some best practice tweaks as well as some new strategies you can start implementing. Here is a good article with some tips as well: http://learn.shayhowe.com/html-css/writing-your-best-code/

**Comment by Rupieeroo** [comment]
Thank you for your feedback, very helpful and hopefully I can correct these mistakes in future projects!
